{"uuid": "fae4a51c-02d6-4565-ba6d-40ce4c4eed94", "children": ["fa21bfdc-8847-464b-86a6-2da4c0209c2f", "341e5545-d35e-4d78-acd7-ce47986f1723", "fcb01404-f453-484e-99dc-fe9592c98879", "f403879a-8b82-43fd-acfa-f812a75037ac"], "befores": [{"name": "_Class__pytest_setup_class", "status": "broken", "statusDetails": {"message": "TypeError: setup_class() missing 1 required positional argument: 'self'\n", "trace": "  File \"e:\\python3.8\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"e:\\python3.8\\lib\\site-packages\\_pytest\\fixtures.py\", line 958, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"e:\\python3.8\\lib\\site-packages\\_pytest\\fixtures.py\", line 784, in call_fixture_func\n    res = next(it)\n  File \"e:\\python3.8\\lib\\site-packages\\_pytest\\python.py\", line 722, in xunit_setup_class_fixture\n    _call_with_optional_argument(func, self.obj)\n  File \"e:\\python3.8\\lib\\site-packages\\_pytest\\python.py\", line 660, in _call_with_optional_argument\n    func(arg)\n  File \"E:\\数据分析\\scripts\\test_cal.py\", line 10, in setup_class\n    self.driver = set_tear.setup_class()\n"}, "start": 1593051384985, "stop": 1593051384985}], "start": 1593051384985, "stop": 1593051385301}