{"name": "test_login[15780184497-LyYbuRBT8N]", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: '../data/generate.yml'", "trace": "self = <test_tpshop.TestTPshop object at 0x000001D1DD9B0490>\nusername = '15780184497', password = 'LyYbuRBT8N'\n\n    @pytest.mark.parametrize('username, password', fake_data(10))\n    def test_login(self, username, password):\n>       write_yml_to_file([username, password], 'generate')\n\nscripts\\test_tpshop.py:27: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\npy_object = ['15780184497', 'LyYbuRBT8N'], yaml_file = 'generate'\n\n    def write_yml_to_file(py_object, yaml_file):\n        from ruamel import yaml\n>       with open('../data/'+yaml_file+'.yml', 'a', encoding='utf-8')as f:\nE       FileNotFoundError: [Errno 2] No such file or directory: '../data/generate.yml'\n\nbase\\base_yml.py:15: FileNotFoundError"}, "parameters": [{"name": "username", "value": "'15780184497'"}, {"name": "password", "value": "'LyYbuRBT8N'"}], "start": 1594453250770, "stop": 1594453250770, "uuid": "e6927f74-dfc8-438c-9418-93260150818c", "historyId": "35c245d28ab3698b56ba501d95e9fe47", "testCaseId": "8ce2edbb4d3f11acca29596f7aaac53c", "fullName": "scripts.test_tpshop.TestTPshop#test_login", "labels": [{"name": "parentSuite", "value": "scripts"}, {"name": "suite", "value": "test_tpshop"}, {"name": "subSuite", "value": "TestTPshop"}, {"name": "host", "value": "LAPTOP-7ES49RD3"}, {"name": "thread", "value": "16148-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "scripts.test_tpshop"}]}