{"uuid": "8c0976dc-1d20-4999-b546-480255fa2662", "children": ["13abc503-f380-495c-8b31-d0868aa1249f"], "befores": [{"name": "_Class__pytest_setup_class", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.StaleElementReferenceException: Message: The element 'By.xpath: //*[@text='微信']' does not exist in DOM anymore\n\n", "trace": "  File \"e:\\python3.8\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"e:\\python3.8\\lib\\site-packages\\_pytest\\fixtures.py\", line 958, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"e:\\python3.8\\lib\\site-packages\\_pytest\\fixtures.py\", line 784, in call_fixture_func\n    res = next(it)\n  File \"e:\\python3.8\\lib\\site-packages\\_pytest\\python.py\", line 722, in xunit_setup_class_fixture\n    _call_with_optional_argument(func, self.obj)\n  File \"e:\\python3.8\\lib\\site-packages\\_pytest\\python.py\", line 660, in _call_with_optional_argument\n    func(arg)\n  File \"E:\\数据分析\\scripts\\test_wechat_mini.py\", line 16, in setup_class\n    self.minip_page.swipe_into_minip()\n  File \"E:\\数据分析\\page\\minip_page.py\", line 6, in swipe_into_minip\n    self.click(self.Xpath_loc('text', '微信'))\n  File \"E:\\数据分析\\base\\base_action.py\", line 20, in click\n    self.find_element(loc).click()\n  File \"e:\\python3.8\\lib\\site-packages\\selenium\\webdriver\\remote\\webelement.py\", line 80, in click\n    self._execute(Command.CLICK_ELEMENT)\n  File \"e:\\python3.8\\lib\\site-packages\\selenium\\webdriver\\remote\\webelement.py\", line 633, in _execute\n    return self._parent.execute(command, params)\n  File \"e:\\python3.8\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"e:\\python3.8\\lib\\site-packages\\appium\\webdriver\\errorhandler.py\", line 29, in check_response\n    raise wde\n  File \"e:\\python3.8\\lib\\site-packages\\appium\\webdriver\\errorhandler.py\", line 24, in check_response\n    super(MobileErrorHandler, self).check_response(response)\n  File \"e:\\python3.8\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1595235625473, "stop": 1595235638075}], "start": 1595235625473, "stop": 1595235638391}